#!/usr/bin/env bash

KEY=~/.ssh/eventron.pem
NAME=$1
PROFILE=oregon

if [[ "$NAME" == "S"* ]]; then
	PROFILE=singapore
elif [[ "$NAME" == "F"* ]]; then
	PROFILE=frankfurt
fi

while getopts "k:p:" opt; do
  case $opt in
    p)
      PROFILE=$OPTARG
      ;;
    k)
      KEY=$OPTARG
      ;;
    \?)
      echo "
ERROR: Invalid option. Syntax:

   ec2 instance-name [options]
"
      exit 1
      ;;
  esac
done

IP=$(aws ec2  --profile $PROFILE describe-instances --filter Name=tag:Name,Values=$NAME | grep PublicIpAddress | sed 's/.*: "\([^"]*\).*/\1/')

if [[ "$IP" != "" ]]; then
	echo "Ssh-ing $IP"
	ssh -oStrictHostKeyChecking=no -i $KEY ec2-user@$IP
else
	echo "Instance not found."
fi
